name: CI - Test Chatbot

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run basic test (load model)
      run: |
        python -c "from utils import load_model; model, _ = load_model(); print('Model loaded OK')"
    - name: Lint code
      uses: pre-commit/action@v2.0.3
      # Note: Install pre-commit locally if needed for full linting
